//! Generates `themes_generated.rs` listing every `.theme` file in `themes/`.
//!
//! The generated file is `include!`d from `theme::builtin` and exposes
//! `BUILTIN_THEMES: &[(&str, &str)]` — basename → raw file contents — so the
//! 41 vendored btop themes ship inside the binary at zero runtime cost.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let themes_dir = Path::new(&manifest_dir).join("themes");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = Path::new(&out_dir).join("themes_generated.rs");

    println!("cargo:rerun-if-changed=themes");

    let mut entries: Vec<_> = fs::read_dir(&themes_dir)
        .expect("read_dir themes/")
        .filter_map(|r| r.ok())
        .filter(|e| e.path().extension().and_then(|x| x.to_str()) == Some("theme"))
        .collect();
    entries.sort_by_key(|e| e.file_name());

    let mut out = String::from(
        "// AUTO-GENERATED by build.rs — do not edit.\n\
         pub static BUILTIN_THEMES: &[(&str, &str)] = &[\n",
    );
    for entry in entries {
        let path = entry.path();
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("utf8 stem");
        let abs = path.to_string_lossy();
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            stem, abs
        ));
    }
    out.push_str("];\n");

    fs::write(&out_path, out).expect("write themes_generated.rs");
}
