//! Embedded copy of the 41 vendored btop themes.
//!
//! The `BUILTIN_THEMES` table is generated by `build.rs` at compile time —
//! basename → raw `.theme` contents. See `crates/bobtop-tui/build.rs`.

include!(concat!(env!("OUT_DIR"), "/themes_generated.rs"));

/// The default theme name used when the user hasn't selected one. Picked to
/// have a complete, well-defined gradient set.
pub const DEFAULT_THEME_NAME: &str = "dracula";

/// List the names of every built-in theme, in stable alphabetical order.
pub fn builtin_names() -> impl Iterator<Item = &'static str> {
    BUILTIN_THEMES.iter().map(|(name, _)| *name)
}

/// Look up a built-in theme's source by name.
pub fn builtin_source(name: &str) -> Option<&'static str> {
    BUILTIN_THEMES
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, src)| *src)
}
